# Generated by Django 4.1.5 on 2023-02-03 00:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=500)),
                ('arrival_time', models.DateTimeField()),
                ('total_passenger', models.IntegerField()),
                ('can_share', models.BooleanField(default=False)),
                ('trip_status', models.IntegerField(choices=[(4, 'Complete'), (3, 'In Trip'), (2, 'Confirmed'), (1, 'Open'), (5, 'Canel')])),
                ('share_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'N/A'), ('2', 'X'), ('3', 'XL')], default='1', max_length=4)),
                ('plante_num', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('max_passenger', models.IntegerField(default=0)),
                ('available_status', models.BooleanField(default=True)),
                ('special_info', models.TextField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
