# Generated by Django 4.1.5 on 2023-02-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_id',
            field=models.IntegerField(default=1),
        ),
    ]
