# Generated by Django 3.2.17 on 2023-02-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_driver_id_order_rider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('1', 'N/A'), ('2', 'SEDAN'), ('3', 'COUPE'), ('4', 'SUV'), ('5', 'MPV')], default='1', max_length=10),
        ),
    ]
