# Generated by Django 4.1.5 on 2023-02-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_rider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trip_status',
            field=models.IntegerField(choices=[(4, 'Complete'), (3, 'In Trip'), (2, 'Confirmed'), (1, 'Open'), (5, 'Canel')], default=1),
        ),
    ]
