# Generated by Django 4.1.5 on 2023-02-03 22:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='share_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None),
        ),
    ]
