# Generated by Django 4.1.5 on 2023-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_rider_id_alter_order_share_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_id',
            field=models.IntegerField(default=0),
        ),
    ]
