# Generated by Django 4.1.5 on 2023-02-06 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_share_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='share_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
