# Generated by Django 4.1.5 on 2023-02-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_share_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.IntegerField(default=0)),
                ('share_ids', models.IntegerField(default=0)),
                ('share_passsenger', models.IntegerField(default=0)),
            ],
        ),
    ]
