# Generated by Django 4.1.5 on 2023-02-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='share_ids',
            new_name='share_id',
        ),
    ]
