# Generated by Django 4.1.5 on 2023-02-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_share_ids_share_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_id',
            field=models.CharField(max_length=50),
        ),
    ]
